name: Trigger cache deprecation

on:
  push:

jobs:
  cache:
    runs-on: ubuntu-latest
    steps:
      - name: use cache v4.2.0 referenced by GIT SHA
        uses: actions/cache@1bd1e32a3bdc45362d1e726936510720a7c30a57 # v4.2.0
        with:
          path: .
          key: foo
