name: Trigger cache deprecation

on:
  push:

jobs:
  cache:
    runs-on: ubuntu-latest
    steps:
      - name: use cache v4.1.2 referenced by GIT SHA
        uses: actions/cache@6849a6489940f00c2f30c0fb92c6274307ccb58a # v4.1.2
        with:
          path: .
          key: foo
