name: Trigger cache deprecation

on:
  push:

jobs:
  cache:
    runs-on: ubuntu-latest
    steps:
      - name: use cache v4.0.0 referenced by GIT SHA
        uses: actions/cache@13aacd865c20de90d75de3b17ebe84f7a17d57d2 # v4.0.0
        with:
          path: .
          key: foo
