name: Trigger cache deprecation

on:
  push:

jobs:
  cache:
    runs-on: ubuntu-latest
    steps:
      - name: use cache
        uses: actions/cache@v4.1.2
        with:
          path: .
          key: foo
